const now = new Date()
const currentYear = now.getFullYear()
const currentMonth = now.getMonth()
const dateForDay = (day, hour, minute = 15) =>
    new Date(currentYear, currentMonth, day, hour, minute, 0).toISOString()
const addHours = (iso, hours) => new Date(new Date(iso).getTime() + hours * 60 * 60 * 1000).toISOString()
const todayDemoCheckIn = new Date(currentYear, currentMonth, now.getDate(), 9, 5, 0).toISOString()
const todayDemoCheckOut = addHours(todayDemoCheckIn, 8.5)

const users = [
    { id: 'user-1', name: 'Admin User', email: 'admin@bloemist.com', phone: '+1 555-1234', role: 'admin', status: 'active', createdAt: new Date().toISOString() },
    { id: 'user-2', name: 'Sarah Chen', email: 'sarah@bloemist.com', phone: '+1 555-2222', role: 'florist', status: 'active', avatar: '🌸', createdAt: new Date().toISOString() },
    { id: 'user-4', name: 'Nina Patel', email: 'nina@bloemist.com', phone: '+1 555-4444', role: 'sales', status: 'active', avatar: '📞', createdAt: new Date().toISOString() },
    { id: 'user-5', name: 'Marco Ruiz', email: 'marco@bloemist.com', phone: '+1 555-5555', role: 'florist', status: 'active', avatar: '🎨', createdAt: new Date().toISOString() },
    { id: 'user-6', name: 'Jessie Dao', email: 'jessie@bloemist.com', phone: '+1 555-6666', role: 'sales', status: 'active', avatar: '⚡', createdAt: new Date().toISOString() },
    { id: 'boss-1', name: 'The Boss', email: 'boss@bloemist.com', phone: '+1 555-9999', role: 'boss', status: 'active', avatar: '🕴️', createdAt: new Date().toISOString() },
    { id: 'user-miguel', name: 'Miguel Santos', email: 'miguel@bloemist.com', phone: '+1 555-7777', role: 'florist', status: 'active', createdAt: new Date().toISOString() },
    { id: 'user-priya', name: 'Priya Kapoor', email: 'priya@bloemist.com', phone: '+1 555-8888', role: 'florist', status: 'active', createdAt: new Date().toISOString() },
    { id: 'user-olivia', name: 'Olivia Reyes', email: 'olivia@bloemist.com', phone: '+1 555-3333', role: 'florist', status: 'active', createdAt: new Date().toISOString() },
];

const orders = [
    {
        id: 'order-1',
        code: 'ORD-2041',
        customerName: 'Amelia Johnson',
        customerPhone: '+1 555-2011',
        receiverName: 'Oliver Johnson',
        receiverPhone: '+1 555-5011',
        bouquetName: 'Sunset Peony Deluxe',
        bouquetImage: '/red-roses-bouquet.png',
        receiveTime: new Date().toISOString(),
        deliveryType: 'DELIVERY',
        status: 'IN_PROGRESS',
        listedPrice: '185,000',
        discount: '0',
        deliveryFee: '15,000',
        deliveryCoveredByShop: false,
        vatPercent: 8,
        deposit: '50,000',
        sellingPrice: '199,800',
        remainingBalance: '164,800',
        total: '214,800',
        notes: 'Deliver to concierge, ribbon must be coral',
        createdById: 'user-1',
        createdByName: 'Admin User',
    },
    {
        id: 'order-2',
        code: 'ORD-2042',
        customerName: 'Benjamin Lee',
        customerPhone: '+1 555-2788',
        receiverName: 'Isabella Lee',
        receiverPhone: '+1 555-6992',
        bouquetName: 'Garden Party Posy',
        bouquetImage: '/spring-flowers-mixed.jpg',
        receiveTime: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
        deliveryType: 'PICKUP',
        status: 'NEW',
        listedPrice: '120,000',
        discount: '25,000',
        deliveryFee: '0',
        deliveryCoveredByShop: true,
        vatPercent: 5,
        deposit: '20,000',
        sellingPrice: '99,750',
        remainingBalance: '79,750',
        total: '99,750',
        createdById: 'user-1',
        createdByName: 'Admin User',
    },
    {
        id: 'order-3',
        code: 'ORD-2043',
        customerName: 'Lena Gomez',
        customerPhone: '+1 555-1234',
        receiverName: 'Marco Gomez',
        receiverPhone: '+1 555-3333',
        bouquetName: 'Wild Meadow Cascade',
        bouquetImage: '/sunset-orange-flowers.jpg',
        receiveTime: new Date(Date.now() + 1000 * 60 * 90).toISOString(),
        deliveryType: 'DELIVERY',
        status: 'IN_PROGRESS',
        listedPrice: '150,000',
        discount: '10,000',
        deliveryFee: '12,000',
        deliveryCoveredByShop: false,
        vatPercent: 10,
        deposit: '60,000',
        sellingPrice: '154,000',
        remainingBalance: '106,000',
        total: '166,000',
        notes: 'Add baby\'s breath accent',
        createdById: 'user-1',
        createdByName: 'Admin User',
    },
]

const tasks = [
    {
        id: 'task-1',
        orderId: 'order-1',
        orderCode: 'ORD-2041',
        bouquetName: 'Sunset Peony Deluxe',
        bouquetImage: '/red-roses-bouquet.png',
        taskTitle: 'Build Sunset Peony Deluxe for Amelia Johnson',
        price: '₫185,000',
        assigneeId: 'user-2',
        assigneeName: 'Sarah Chen',
        status: 'ASSIGNED',
        dueTime: new Date(Date.now() + 1000 * 60 * 60 * 3).toISOString(),
        createdAt: new Date().toISOString(),
        startTime: null,
        notes: 'Use coral silk ribbon and include note card',
        type: 'CAM_HOA',
        quantity: 1,
        customerName: 'Amelia Johnson',
        customerPhone: '+1 555-2011',
        receiverName: 'Oliver Johnson',
        receiverPhone: '+1 555-5011',
        deliveryType: 'DELIVERY',
        deliveryTime: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
        samplePhotoUrls: ['/red-roses-bouquet.png'],
    },
    {
        id: 'task-2',
        orderId: 'order-2',
        orderCode: 'ORD-2042',
        bouquetName: 'Garden Party Posy',
        bouquetImage: '/spring-flowers-mixed.jpg',
        taskTitle: 'Garden Party Posy – pickup order',
        price: '₫95,000',
        status: 'UNASSIGNED',
        dueTime: new Date(Date.now() + 1000 * 60 * 60).toISOString(),
        createdAt: new Date().toISOString(),
        startTime: null,
        notes: 'Customer loves lavender scent',
        type: 'CAM_HOA',
        quantity: 1,
        customerName: 'Benjamin Lee',
        customerPhone: '+1 555-2788',
        receiverName: 'Isabella Lee',
        receiverPhone: '+1 555-6992',
        deliveryType: 'PICKUP',
        deliveryTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
        samplePhotoUrls: ['/spring-flowers-mixed.jpg'],
    },
    {
        id: 'task-3',
        orderId: 'order-3',
        orderCode: 'ORD-2043',
        bouquetName: 'Wild Meadow Cascade',
        bouquetImage: '/sunset-orange-flowers.jpg',
        taskTitle: 'Wild Meadow Cascade for Lena',
        price: '₫120,000',
        assigneeId: 'user-miguel',
        assigneeName: 'Miguel Santos',
        status: 'READY',
        dueTime: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
        createdAt: new Date().toISOString(),
        startTime: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        notes: 'Cascade shape should be airy',
        type: 'CAM_HOA',
        quantity: 1,
        customerName: 'Lena Gomez',
        customerPhone: '+1 555-1234',
        receiverName: 'Marco Gomez',
        receiverPhone: '+1 555-3333',
        deliveryType: 'DELIVERY',
        deliveryTime: new Date(Date.now() + 1000 * 60 * 120).toISOString(),
        samplePhotoUrls: ['/sunset-orange-flowers.jpg'],
    },
]

const staffCheckins = [
    {
        id: 'checkin-today-demo',
        staffId: 'user-2',
        staffName: 'Sarah Chen',
        discipline: 'florist',
        timestamp: todayDemoCheckIn,
        checkInAt: todayDemoCheckIn,
        checkOutAt: todayDemoCheckOut,
        workingHours: 8.5,
        locationLabel: 'Bloemist Studio — Demo counter',
        locationType: 'AT_OFFICE',
        coordinates: { lat: 37.776, lng: -122.41 },
        distanceFromOfficeKm: 0.1,
        ordersTouched: 2,
        completedTasks: 1,
        notes: 'Demo check-in and check-out for today',
    },
    {
        id: 'checkin-1',
        staffId: 'user-2',
        staffName: 'Sarah Chen',
        discipline: 'florist',
        timestamp: dateForDay(2, 8),
        checkInAt: dateForDay(2, 8),
        checkOutAt: addHours(dateForDay(2, 8), 8),
        workingHours: 8,
        locationLabel: 'Bloemist Studio — Main Workbench',
        locationType: 'AT_OFFICE',
        coordinates: { lat: 37.776, lng: -122.41 },
        distanceFromOfficeKm: 0.1,
        ordersTouched: 1,
        completedTasks: 2,
        notes: 'Prepping wedding centerpieces',
    },
    {
        id: 'checkin-2',
        staffId: 'user-2',
        staffName: 'Sarah Chen',
        discipline: 'florist',
        timestamp: dateForDay(5, 14),
        checkInAt: dateForDay(5, 14),
        checkOutAt: addHours(dateForDay(5, 14), 7.5),
        workingHours: 7.5,
        locationLabel: 'Client delivery — Pacific Heights',
        locationType: 'FIELD',
        coordinates: { lat: 37.792, lng: -122.434 },
        distanceFromOfficeKm: 4.7,
        ordersTouched: 2,
        completedTasks: 1,
        notes: 'On-site install for event',
        requiresReview: true,
        verificationStatus: 'approved',
        verificationNote: 'Venue install photos attached',
    },
    {
        id: 'checkin-3',
        staffId: 'user-2',
        staffName: 'Sarah Chen',
        discipline: 'florist',
        timestamp: dateForDay(9, 9),
        checkInAt: dateForDay(9, 9),
        checkOutAt: addHours(dateForDay(9, 9), 8.25),
        workingHours: 8.25,
        locationLabel: 'Bloemist Studio — Cooler',
        locationType: 'AT_OFFICE',
        coordinates: { lat: 37.776, lng: -122.41 },
        distanceFromOfficeKm: 0.1,
        ordersTouched: 1,
        completedTasks: 3,
    },
    {
        id: 'checkin-4',
        staffId: 'user-2',
        staffName: 'Sarah Chen',
        discipline: 'florist',
        timestamp: dateForDay(12, 7, 45),
        checkInAt: dateForDay(12, 7, 45),
        checkOutAt: addHours(dateForDay(12, 7, 45), 9),
        workingHours: 9,
        locationLabel: 'Wholesale Market — Flower Mart',
        locationType: 'FIELD',
        coordinates: { lat: 37.772, lng: -122.407 },
        distanceFromOfficeKm: 1.6,
        ordersTouched: 0,
        completedTasks: 2,
        notes: 'Sourcing ranunculus',
    },
    {
        id: 'checkin-4b',
        staffId: 'user-2',
        staffName: 'Sarah Chen',
        discipline: 'florist',
        timestamp: dateForDay(18, 15, 10),
        checkInAt: dateForDay(18, 15, 10),
        checkOutAt: addHours(dateForDay(18, 15, 10), 10.5),
        workingHours: 10.5,
        locationLabel: 'Sonoma vineyard ceremony site',
        locationType: 'FIELD',
        coordinates: { lat: 38.291, lng: -122.458 },
        distanceFromOfficeKm: 59.2,
        ordersTouched: 1,
        completedTasks: 4,
        notes: 'Full-day destination wedding install',
        requiresReview: true,
        verificationStatus: 'pending',
        verificationNote: 'Awaiting gallery upload',
    },
    {
        id: 'checkin-5',
        staffId: 'user-4',
        staffName: 'Nina Patel',
        discipline: 'sales',
        timestamp: dateForDay(3, 8, 30),
        checkInAt: dateForDay(3, 8, 30),
        checkOutAt: addHours(dateForDay(3, 8, 30), 8),
        workingHours: 8,
        locationLabel: 'Bloemist Studio — Sales Desk',
        locationType: 'AT_OFFICE',
        coordinates: { lat: 37.776, lng: -122.41 },
        distanceFromOfficeKm: 0.1,
        ordersTouched: 6,
        completedTasks: 0,
    },
    {
        id: 'checkin-6',
        staffId: 'user-4',
        staffName: 'Nina Patel',
        discipline: 'sales',
        timestamp: dateForDay(7, 11),
        checkInAt: dateForDay(7, 11),
        checkOutAt: addHours(dateForDay(7, 11), 7),
        workingHours: 7,
        locationLabel: 'Client visit — Salesforce Park',
        locationType: 'FIELD',
        coordinates: { lat: 37.789, lng: -122.398 },
        distanceFromOfficeKm: 2.1,
        ordersTouched: 3,
        completedTasks: 0,
        notes: 'Corporate subscription renewal',
    },
    {
        id: 'checkin-6b',
        staffId: 'user-4',
        staffName: 'Nina Patel',
        discipline: 'sales',
        timestamp: dateForDay(19, 16, 45),
        checkInAt: dateForDay(19, 16, 45),
        checkOutAt: addHours(dateForDay(19, 16, 45), 9.25),
        workingHours: 9.25,
        locationLabel: 'South Bay enterprise client visit',
        locationType: 'FIELD',
        coordinates: { lat: 37.387, lng: -122.057 },
        distanceFromOfficeKm: 52.8,
        ordersTouched: 5,
        completedTasks: 0,
        notes: 'Quarterly renewal + upsell',
        requiresReview: true,
        verificationStatus: 'pending',
        verificationNote: 'Needs mileage log',
    },
    {
        id: 'checkin-7',
        staffId: 'user-5',
        staffName: 'Marco Ruiz',
        discipline: 'florist',
        timestamp: dateForDay(4, 7, 50),
        checkInAt: dateForDay(4, 7, 50),
        checkOutAt: addHours(dateForDay(4, 7, 50), 8.5),
        workingHours: 8.5,
        locationLabel: 'Bloemist Studio — Design Table',
        locationType: 'AT_OFFICE',
        coordinates: { lat: 37.776, lng: -122.41 },
        distanceFromOfficeKm: 0.1,
        ordersTouched: 1,
        completedTasks: 4,
    },
    {
        id: 'checkin-8',
        staffId: 'user-5',
        staffName: 'Marco Ruiz',
        discipline: 'florist',
        timestamp: dateForDay(10, 13, 5),
        checkInAt: dateForDay(10, 13, 5),
        checkOutAt: addHours(dateForDay(10, 13, 5), 9),
        workingHours: 9,
        locationLabel: 'Venue setup — Ferry Building',
        locationType: 'FIELD',
        coordinates: { lat: 37.795, lng: -122.393 },
        distanceFromOfficeKm: 3.4,
        ordersTouched: 1,
        completedTasks: 5,
        notes: 'Install ceremony arch',
        requiresReview: true,
        verificationStatus: 'approved',
        verificationNote: 'Event photos confirmed attendance',
    },
    {
        id: 'checkin-9',
        staffId: 'user-5',
        staffName: 'Marco Ruiz',
        discipline: 'florist',
        timestamp: dateForDay(21, 18, 30),
        checkInAt: dateForDay(21, 18, 30),
        checkOutAt: addHours(dateForDay(21, 18, 30), 6.25),
        workingHours: 6.25,
        locationLabel: 'Napa delivery — Silverado Resort',
        locationType: 'FIELD',
        coordinates: { lat: 38.337, lng: -122.300 },
        distanceFromOfficeKm: 77.4,
        ordersTouched: 2,
        completedTasks: 3,
        notes: 'High-value elopement drop-off',
        requiresReview: true,
        verificationStatus: 'flagged',
        verificationNote: 'Delivery signature missing',
    },
    {
        id: 'checkin-10',
        staffId: 'user-6',
        staffName: 'Jessie Dao',
        discipline: 'hybrid',
        timestamp: dateForDay(6, 9, 5),
        checkInAt: dateForDay(6, 9, 5),
        checkOutAt: addHours(dateForDay(6, 9, 5), 8.5),
        workingHours: 8.5,
        locationLabel: 'Bloemist Studio — Customer lounge',
        locationType: 'AT_OFFICE',
        coordinates: { lat: 37.776, lng: -122.41 },
        distanceFromOfficeKm: 0.1,
        ordersTouched: 4,
        completedTasks: 2,
        notes: 'Bridging rush delivery between sales and production',
    },
    {
        id: 'checkin-11',
        staffId: 'user-6',
        staffName: 'Jessie Dao',
        discipline: 'hybrid',
        timestamp: dateForDay(15, 14, 20),
        checkInAt: dateForDay(15, 14, 20),
        checkOutAt: addHours(dateForDay(15, 14, 20), 7.75),
        workingHours: 7.75,
        locationLabel: 'Client consult — Dogpatch loft',
        locationType: 'FIELD',
        coordinates: { lat: 37.7608, lng: -122.388 },
        distanceFromOfficeKm: 3.7,
        ordersTouched: 2,
        completedTasks: 1,
        notes: 'Scoped build + upsold installation',
        requiresReview: true,
        verificationStatus: 'approved',
        verificationNote: 'Signed quote uploaded',
    },
]

const workspaceSettings = {
    storeLocations: [
        {
            id: 'store-main',
            label: 'Bloemist Studio — Main Entrance',
            address: '123 Market St, San Francisco',
            coordinates: { lat: 37.776, lng: -122.41 },
        },
        {
            id: 'store-north',
            label: 'North Beach Popup',
            address: 'Columbus Ave, San Francisco',
            coordinates: { lat: 37.799, lng: -122.408 },
        },
    ],
    workingHours: {
        start: '08:00',
        end: '18:00',
    },
}

module.exports = {
    users,
    orders,
    tasks,
    staffCheckins,
    workspaceSettings
};
